package jdbc;
// Generated Aug 23, 2017 7:58:06 PM by Hibernate Tools 4.3.1



/**
 * Userinfo generated by hbm2java
 */
public class Userinfo  implements java.io.Serializable {


     private String username;
     private String name;
     private String address;
     private byte[] propic;
     private String contact;
     private String gender;
     //private String email;

    public Userinfo() {
    }

	
    public Userinfo(String username, String name, String address, String contact, String gender) {
        this.username = username;
        this.name = name;
        this.address = address;
        this.contact = contact;
        this.gender = gender;
       
    }
    public Userinfo(String username, String name, String address, byte[] propic, String contact, String gender) {
       this.username = username;
       this.name = name;
       this.address = address;
       this.propic = propic;
       this.contact = contact;
       this.gender = gender;
      
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public byte[] getPropic() {
        return this.propic;
    }
    
    public void setPropic(byte[] propic) {
        this.propic = propic;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
  




}


